- .circleci/config.yml
- .pre-commit-config.yaml
- README.md
- main.tf
- outputs.tf
- variables.tf
Having CloudTrail send events to CloudWatch Logs means we can start generating alarms and filters around certain sensitive events like disabling CloudTrail :). I also update the CircleCI image, pre-commit hooks and general comment cleanup.
> Add support for sending CloudTrail events to CloudWatch Logs.

- .circleci/config.yml
- .pre-commit-config.yaml
- README.md
- main.tf
Readme used 
`source         = "trussworks/aws/logs"`
updated to 
`source         = "trussworks/logs/aws"`
Also have changed README to autoupdate.
> update readme to reflect accurate var name

- README.md
- main.tf
- policy.tpl
- variables.tf
This PR enables CloudWatch exports to the S3 bucket, which would be useful for creating backups of logs during delicate infrastructure operations.
> Enable CloudWatch Exports

- README.md
- main.tf
- variables.tf
We want to be able to set the cloudwatch log group retention separately from the expiration variable because the log group retention has a very specific policy around the number of days you can set it to. Decoupling these variables will allow us to throw off the yoke of that repressive policy for the lifecycle rule regarding log expiration for the aws_s3_bucket.
> separate cloudwatch log group retention var from aws log expiration var

- main.tf
I changed the name of the key for the lifecycle rule when it should've been left "expiration".
> fix var name

- .circleci/config.yml
- README.md
The docker image is pretty old for testing against.
> Update circleci docker image

- README.md
- main.tf
- variables.tf
I discovered that the NLB is not doing access logging in https://github.com/trussworks/terraform-aws-nlb-containers/pull/9. However, to enable access logging the bucket must allow the NLB to write.
> Allow an NLB to log to the S3 logging bucket

- main.tf
- variables.tf
Some companies (like mine) don't allow standard developers to modify the public access block since we do it at the account level. They get the following error (which isn't super helpful)
> error creating public access block policy for S3 bucket (...): AccessDenied: Access Denied
> status code: 403
This would allow end users to opt out of the block if they're unable to create one themselves. Not sure if you would want to add some sort of caveat that they should ensure it's being protected in other ways (eg, an account-wide block).
> Make creation of public_access_block optional

- README.md
CircleCI failed on the merge to master because the README wasn't up to date. This is because we don't run CircleCI tests against forked PRs. This is intentional as prevents folks from running arbitrary code under our CircleCI project.
At any rate, this fixes the README (and the master branch).
> Generate README

- README.md
- main.tf
tl;dr - Lock down bucket policies to the owner's account.
We noticed in our S3 bucket that AWS Config logs had been delivered from a different account. After investigating with AWS Support it appeared that our IAM policies were too permissive. Further investigation revealed that when I had been playing with AWS Config from a different account I used the same bucket name as my customer project so that my own logs went to the customer's S3 bucket. 
Fortunately AWS Support has confirmed that our bucket policies give the S3 bucket owner full ownership permissions and that my personal AWS account cannot access or read those logs.  This PR simply closes a potential hole where someone could abuse a service on a different account and cause it to log too many objects to our account.
> Secure S3 bucket from being written to by services on different accounts

- .circleci/config.yml
- README.md
- main.tf
- variables.tf
Application Load Balancers were actually logging to a different prefix than assumed.  This PR allows us to limit bucket policy by multiple prefixes correctly.
> fix to properly support ALB customizations

- README.md
- examples/cloudtrail/main.tf
- examples/cloudtrail/variables.tf
- main.tf
- test/terraform_aws_logs_cloudtrail_test.go
Prior to this change, attempts to create a cloudtrail using this logs
bucket would fail initially with an InsufficientS3BucketPolicyException.
It was an ordering issue, where the cloudtrail would attempt to use the
s3 bucket before the subsequent policy attachment was complete. Running
a second terraform apply would work, but the logs bucket and cloudtrail
should be able to be created in the same terraform apply.
This change removes the aws_s3_bucket_policy resource and applies the
bucket policy directly in the aws_s3_bucket resource.
https://www.pivotaltracker.com/story/show/169575508
This PR adds a new terratest. Running the two terratests against our CI AWS account returns:
--- PASS: TestTerraformAwsLogs (34.94s)
--- PASS: TestTerraformAwsLogsCloudtrail (48.01s)
PASS
ok …
> Apply bucket policy directly to bucket resource

- .circleci/config.yml
- .gitignore
- .pre-commit-config.yaml
- README.md
- main.tf
- variables.tf
This PR add support for a custom list of NLB prefixes that reflects how the ALB prefixes is handled.
> Use nlb_logs_prefixes instead of nlb_logs_prefix

- README.md
On further reflection we want to have a better understanding of the weirdness with how Cloudfront is granting itself access to the logs bucket & some kind of plan for handling a possible future world where that changes before we document support.
> Revert "Document that Cloudfront is supported"

- .circleci/config.yml
- README.md
- main.tf
This change adds an extra statement to the log S3 bucket policy that
denies requests unless they're made via TLS.
This additional policy statement is necessary to be able to enforce
encryption-in-transit requirements alongside the encryption-at-rest
that's already handled by the
`apply_server_side_encryption_by_default` block on the S3 bucket
resource.
This policy is required for buckets managed by this module to pass the
AWS Config `s3-bucket-ssl-requests-only`[1] managed rule and
Prowler's[2] `extra764` check, which although not part of the CIS
benchmark seems like a sensible thing to satisfy.
Note that Trussworks' AWS Config module[3] enables the
s3-bucket-ssl-requests-only check by default, so before this change,
the two modules together result in failing Config checks.
A previous PR …
> Enforce TLS requests only by default

- .dependabot/config.yml
Missed this on the last pass.... this enables Dependabot to just do the thing after a merge.
> missing dependabot auto merge

- README.md
- examples/simple/main.tf
- examples/simple/variables.tf
- go.mod
- go.sum
- main.tf
- test/terraform_aws_logs_test.go
- variables.tf
[Pivotal Story](https://www.pivotaltracker.com/story/show/172481131)
This ticket adds a new variable to allow a user of the module to add their own tags to the logs s3 bucket.
This implementation is modeled after [terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/variables.tf#L219)
> Add tags variable to terraform

- README.md
- examples/alb_remote/main.tf
- examples/alb_remote/providers.tf
- examples/alb_remote/variables.tf
- examples/nlb_remote/main.tf
- examples/nlb_remote/providers.tf
- examples/nlb_remote/variables.tf
- main.tf
- test/terraform_aws_logs_alb_test.go
- test/terraform_aws_logs_nlb_test.go
- variables.tf
This PR is to add the support to allow cross account logging for ALB and NLB logs.
This adds the input variable:
- alb_account
- nlb_account
These vars have a default value of "" to not break existing deployments and maintain backwards compatibility. When nothing provided will default to the current AWS account (existing behavior).
When specified will change the resource to match the given account numbers.
Before PR:
`"Resource": "arn:aws-us-gov:s3:::my-bucket/prefix/AWSLogs/11111111111/*"`
After PR provided account `2222222222`:
`"Resource": "arn:aws-us-gov:s3:::my-bucket/prefix/AWSLogs/2222222222/*"`
> Adding alb_account and nlb_account vars

- README.md
- outputs.tf
It's not immediately obvious what "S3 bucket" means from reading docs, so hopefully this change will help with that.
> Clarify bucket output description

- README.md
- versions.tf
Terraform 0.14.x doesn't have syntactical upgrades that require running something like `terraform 0.14upgrade`. So this PR relaxes the versioning constraints so folks on 0.13.x and 0.14.x can keep swimming.
> Relax version constraints so folks can use this module with 0.14.x

- .circleci/config.yml
- .pre-commit-config.yaml
- README.md
- examples/alb/providers.tf
- examples/alb_remote/providers.tf
- examples/cloudtrail/providers.tf
- examples/combined/providers.tf
- examples/config/providers.tf
- examples/elb/providers.tf
- examples/logging_target_bucket/providers.tf
- examples/nlb/providers.tf
- examples/nlb_remote/providers.tf
- examples/redshift/providers.tf
- examples/s3/providers.tf
- examples/simple/providers.tf
- versions.tf
We've already relaxed the version constraints to allow Terraform 0.14 to use this module. This PR will run the terratests on 0.14 and remove support for 0.11. Lastly, this PR cleans up the CircleCI config and updates pre-commit hooks.  
Once merged, I will remove the `terraform011` branch.
> Deprecate Terraform 0.11 and relax version AWS provider version constraints.

- README.md
- examples/versioning/main.tf
- examples/versioning/variables.tf
- main.tf
- test/terraform_aws_logs_versioning.go
- variables.tf
CMS has a requirement to add versioning to S3 buckets, so adding this as an option will give us one less thing to worry about. I set versioning off by default, since that was the previous functionality, and added a lifecycle rule to purge noncurrent versions of objects after a number of days specified in another variable (default 30).
> Adding support for versioning of logs buckets

- README.md
- versions.tf
Lots of breaking changes around s3 resources coming in the [4.0 version of the AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/20433).  This PR prevents us from falling into those breaking changes until we've made the necessary fixes.
> Restrict to 3.x of the aws provider in anticipation of breaking changes

- .pre-commit-config.yaml
- README.md
- examples/combined/main.tf
- examples/logging_target_bucket/main.tf
- examples/s3/main.tf
- main.tf
- variables.tf
- versions.tf
Saw that this wasn't updated to v4 of the AWS provider, so I've gone through and moved all the blocks out of the `aws_s3_bucket` resource and into the various individual s3 config pieces. I believe the upgrade process should be pretty transparent.
I've tested this with a repo running v3 and it works with no warnings.
> Updating for aws v4 provider (and a little cleanup of the pre-commit hooks)

- README.md
This adds version upgrade guidance for going from v11 to v12. Additionally, it removes information about pinning Terraform versions to specific branches since we're now at 1.x. Finally, it adds guidance for upgrading from v10 to v11of this module.
> add upgrade instructions to v12

- examples/cloudtrail/main.tf
- examples/combined/main.tf
This addresses a couple issues where name conflicts can occur during CI tests:
```
╷
│ Error: Error creating CloudTrail: TrailAlreadyExistsException: Trail cloudtrail already exists for customer: 313564602749
│ 
│   with module.aws_cloudtrail.aws_cloudtrail.main,
│   on .terraform/modules/aws_cloudtrail/main.tf line 246, in resource "aws_cloudtrail" "main":
│  246: resource "aws_cloudtrail" "main" {
│ 
╵}
```
or
```
│ Error: failed creating IAM Role (cloudtrail-cloudwatch-logs-role): EntityAlreadyExists: Role with name cloudtrail-cloudwatch-logs-role already exists.
│ 	status code: 409, request id: a4d3a784-4eb8-467e-8bd7-8a2a29fc0632
│ 
│   with module.aws_cloudtrail.aws_iam_role.cloudtrail_cloudwatch_role,
│   on .terraform/modules/aws_cloudtrail/main.tf line 32, in resource …
```
> address conflicting iam role and cloudtrail names

- main.tf
Ignore changes to the `lifecycle_rule` and `server_side_encryption_configuration` keys in the `aws_s3_bucket` resource to allow for upgrades to 4.x of the AWS provider.
This is based off the recommendations here:
- [aws_s3_bucket_lifecycle_configuration  usage notes](https://github.com/hashicorp/terraform-provider-aws/blob/v3.75.1/website/docs/r/s3_bucket_lifecycle_configuration.html.markdown#usage-notes)
- [aws_s3_bucket_server_side_encryption_configuration  usage notes](https://github.com/hashicorp/terraform-provider-aws/blob/v3.75.1/website/docs/r/s3_bucket_server_side_encryption_configuration.html.markdown#usage-notes)
> add backwards compatibility to aws_s3_bucket

- README.md
This updates the upgrade instructions for the v12 upgrade.
`private` should be `log-delivery-write` because of this: https://github.com/trussworks/terraform-aws-logs/blob/8df4fc1f7ba7a9fc1fd09d39444377b451f43f59/variables.tf#L18-L22
This also indicates that one of the import commands is optional.
> fix the 11 -> 12 upgrade instructions

- examples/cloudtrail/main.tf
- examples/combined/main.tf
This is a follow-up to the remaining issue from https://github.com/trussworks/terraform-aws-logs/pull/269
It addresses name conflicts with the IAM policy name stood up by the cloudtrail module, such as this:
```
│ Error: error creating IAM Policy cloudtrail-cloudwatch-logs-policy: EntityAlreadyExists: A policy called cloudtrail-cloudwatch-logs-policy already exists. Duplicate names are not allowed.
│ 	status code: 409, request id: ...
│ 
│   with module.aws_cloudtrail.aws_iam_policy.cloudtrail_cloudwatch_logs,
│   on .terraform/modules/aws_cloudtrail/main.tf line 60, in resource "aws_iam_policy" "cloudtrail_cloudwatch_logs":
│   60: resource "aws_iam_policy" "cloudtrail_cloudwatch_logs" {
│ 
```
> avoid policy name conflicts in ci

- main.tf
Remove filter `/*` from lifecycle rules as it's not working with subdirectory approach to the logs (i.e. if we want alb logs under `alb` path etc.).
> Remove filter `/*` as it's redundant and invalid

- README.md
- examples/custom_bucket_policy/main.tf
- examples/custom_bucket_policy/variables.tf
- outputs.tf
Changes proposed in this pull request:
- adds the bucket arn to output
- adds example for updating/using a custom bucket policy
> NT: adds arn as output and custom bucket policy example

- README.md
- main.tf
- variables.tf
Resolves #307 
Updates the module to account for changes made by AWS in April 2023 to the default security settings of new S3 buckets.
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
See the proposed changes in the README `Upgrade Paths` section for more details about the module changes.
If approved, the plan is to release this as a major version update.
> Update the module based on AWS changes to S3 bucket default settings

- .pre-commit-config.yaml
- README.md
- versions.tf
-     Modified README
-     Set expected terraform version to be equal or greater than Terraform version 1.0
> Deprecate support for ancient terraform versions in our modules

- README.md
- main.tf
In response to the following warning:
```
│ Warning: Deprecated Resource
│
│   with module.logs.data.aws_redshift_service_account.main,
│   on .terraform/modules/logs/main.tf line 8, in data "aws_redshift_service_account" "main":
│    8: data "aws_redshift_service_account" "main" {
│
│ The aws_redshift_service_account data source has been deprecated and will be removed in a future version. Use a service principal name instead of AWS
│ account ID in any relevant IAM policy.
```
> Removes the redshift service account and switches to service principal

- .github/workflows/validate.yml
- .gitignore
- .golangci.yml
- .markdownlintrc
- .pre-commit-config.yaml
- .terraform-docs.yml
- README.md
- examples/logging_target_bucket/main.tf
- main.tf
- renovate.json
- variables.tf
This copies `aws_s3_server_side_encryption_configuration` from `terraform-aws-s3-private-bucket` [here](https://github.com/trussworks/terraform-aws-s3-private-bucket/blob/main/main.tf#L264-L274). This adds two supporting variables `kms_master_key_id` and `bucket_key_enabled`. As defined, this contiues to support `AES256` as the default algorithm that the current module supports.
`elb_log_prefixes` is changed from a `string` to a `list(string)` as `resources` in an `iam_policy_document` expects `resources` to be a list. This mirrors `nlb_log_prefixes` and `alb_log_refixes` which are already `list(string)` types.
- **chore: remove unnecessary file**
- **chore: pinning github action**
- **chore: renovate renovate config**
- **chore: ignore lock file**
- **chore: pre-commit autoupdate**
- …
> feat: Support passing KMS key to bucket encryption configuration

- variables.tf
- versions.tf
When attempting a `terraform plan` encountered this error:
```terraform
│ Error: Invalid template interpolation value
│
│   on .terraform/modules/bootstrap.terraform_state_bucket_logs/main.tf line 90, in locals:
│   90:   elb_logs_path = var.elb_logs_prefix == "" ? "AWSLogs" : "${var.elb_logs_prefix}/AWSLogs"
│     ├────────────────
│     │ var.elb_logs_prefix is list of string with 1 element
│
│ Cannot include the given value in a string template: string required.
```
So this sets `elb_logs_prefix` to be a `string` rather than `list(string)`.
> fix: elb_logs_prefix should be string not list(string)

- main.tf
If a user were to define something like 
```terraform
default_allow = false
```
Then run a `terraform plan` and `terraform apply` for the first time, it would result in all `Effects` in the IAM policy to be `Deny`.
Then if a person were to want to enable s3 logging, they would update like so
```terraform
default_allow = false
allow_s3      = true
```
When running a `terraform plan` it would show `No changes. Your infrastucture matches the configuration.` because the `lifecycle` block ignores changes on `policy`.
Also, should the policy get edited on the console in some manner, a `terraform plan` and `terraform apply` would not revert it back to what's in Terraform, it wouldn't detect the drift at all. Not a desired behavior.
> chore: remove lifecycle block on bucket policy

- main.tf
- versions.tf
Similar to what we saw on another module, `data.aws_region.current.name` is deprecated.
```terraform
│ Warning: Deprecated attribute
│
│   on .terraform/modules/logs/main.tf line 6, in locals:
│    6:   ["ap-south-2", "ap-southeast-4", "ap-southeast-5", "ap-southeast-7", "ca-west-1", "eu-south-2", "eu-central-2", "il-central-1", "me-central-1"], data.aws_region.current.name)
│
│ The attribute "name" is deprecated. Refer to the provider documentation for details.
│
│ (and one more similar warning elsewhere)
│ Warning: Deprecated attribute
│
│   on .terraform/modules/logs/main.tf line 63, in locals:
│   63:   cloudwatch_service = "logs.${data.aws_region.current.name}.amazonaws.com"
│
│ The attribute "name" is deprecated. Refer to the provider documentation for details.
╵
Success! The …
```
> fix: name attribute is deprecated
